use core::cmp;

use zerocopy::{FromBytes, Immutable, KnownLayout, Unaligned};

use crate::error::Result;
use crate::io;
use crate::io::Read;

macro_rules! iter_try {
    ($e:expr) => {
        match $e {
            Ok(x) => x,
            Err(e) => return Some(Err(e.into())),
        }
    };
}

/// A simplified `fsmnt_testkit::Cursor`-like type that implements only `Read` but not `Seek`.
///
/// This is all we need inside this crate.
pub(crate) struct ReadOnlyCursor<'a>(&'a [u8]);

impl<'a> ReadOnlyCursor<'a> {
    pub(crate) fn new(data: &'a [u8]) -> Self {
        Self(data)
    }
}

impl Read for ReadOnlyCursor<'_> {
    fn read(&mut self, buf: &mut [u8]) -> io::Result<usize> {
        let bytes_to_read = cmp::min(self.0.len(), buf.len());
        buf[..bytes_to_read].copy_from_slice(&self.0[..bytes_to_read]);
        self.0 = &self.0[bytes_to_read..];

        Ok(bytes_to_read)
    }
}

/// Reads a plain old data structure that implements `zerocopy` traits via `crate::io::Read`.
#[inline]
#[track_caller]
pub(crate) fn read_pod<T, Pod, const LEN: usize>(r: &mut T) -> Result<Pod>
where
    T: Read,
    Pod: FromBytes + Immutable + KnownLayout + Unaligned,
{
    let mut bytes = [0u8; LEN];
    r.read_exact(&mut bytes)?;
    Ok(Pod::read_from_bytes(&bytes).unwrap())
}

/// Reads a UTF-16LE name into an `ArrayVec` buffer, then truncates to the actual length.
pub(crate) fn read_name_into<T, const N: usize>(
    r: &mut T,
    name: &mut arrayvec::ArrayVec<u8, N>,
    name_length: usize,
) -> Result<()>
where
    T: Read,
{
    debug_assert_eq!(name.len(), N);
    r.read_exact(&mut name[..name_length])?;
    name.truncate(name_length);
    Ok(())
}

#[cfg(test)]
pub mod tests {
    use fsmnt_testkit::Cursor;
    use std::fs::File;
    use std::io::Read;
    use std::sync::Once;

    /// Loads the `testdata/testfs1` NTFS image fixture, or returns `None`
    /// when the file is absent. The fixture is generated by
    /// `testdata/create-testfs1.sh` (root + ntfs-3g) and is intentionally
    /// not checked into the repo. Tests that depend on it should treat a
    /// `None` return as "skip cleanly."
    ///
    /// Pattern at the call site:
    /// ```ignore
    /// let Some(mut testfs1) = crate::helpers::tests::testfs1() else { return };
    /// ```
    ///
    /// A one-shot `eprintln!` runs the first time the fixture is observed
    /// to be missing so the skip is visible in test output without
    /// spamming once per test.
    pub fn testfs1() -> Option<Cursor<Vec<u8>>> {
        const PATH: &str = "testdata/testfs1";
        static WARNED: Once = Once::new();

        let Ok(mut file) = File::open(PATH) else {
            WARNED.call_once(|| {
                eprintln!(
                    "skipping fs-ntfs tests that need {PATH}: \
                     fixture not generated (run testdata/create-testfs1.sh)"
                );
            });
            return None;
        };
        let mut buffer = Vec::new();
        file.read_to_end(&mut buffer).ok()?;
        Some(Cursor::new(buffer))
    }
}
