[package]
name = "fsmnt-device"
version.workspace = true
edition.workspace = true

[dependencies]
crc32c = { workspace = true }
ewf = { workspace = true }
fsmnt-core = { workspace = true }
fsmnt-parser-core = { workspace = true, features = ["std"] }
nostdio = { workspace = true, features = ["std"] }
thiserror = { workspace = true }

[lints]
workspace = true
