[package]
name = "fs-fat"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
arbitrary = { workspace = true, optional = true }
bitflags = { workspace = true }
chrono = { workspace = true, optional = true }
fs-common = { workspace = true, default-features = false }
thiserror = { workspace = true }
time = { workspace = true, optional = true }
zerocopy = { workspace = true, features = ["derive"] }

[dev-dependencies]
# Placeholder so `#[mutants::skip]` annotations compile under cargo-mutants.
mutants = "0.0.4"

[features]
default = ["std"]
arbitrary = ["dep:arbitrary"]
std = ["fs-common/std", "thiserror/std", "zerocopy/std"]
chrono = ["dep:chrono"]
time = ["dep:time"]
