[package]
name = "fs-btrfs"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
blake2 = { workspace = true }
crc32c = { workspace = true }
flate2 = { workspace = true, optional = true }
fsmnt-parser-core = { workspace = true, default-features = false }
lzokay = { workspace = true, optional = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
xxhash-rust = { workspace = true }
zstd = { workspace = true, optional = true }
zerocopy = { workspace = true }

[dev-dependencies]
divan = { workspace = true }
fsmnt-testkit = { workspace = true }

[features]
default = []
fuzzing = []
std = [
    "dep:flate2",
    "dep:lzokay",
    "dep:zstd",
    "fsmnt-parser-core/std",
    "thiserror/std",
]

[[bench]]
name = "parser"
harness = false
required-features = ["fuzzing"]

[lints]
workspace = true
