[package]
name = "fs-exfat"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
bitflags = { workspace = true }
chrono = { workspace = true, optional = true }
fsmnt-parser-core = { workspace = true, default-features = false }
thiserror = { workspace = true }
time = { workspace = true, optional = true }
zerocopy = { workspace = true, features = ["derive"] }

[dev-dependencies]
fsmnt-testkit = { workspace = true }
mutants = { workspace = true }

[features]
default = []
std = ["fsmnt-parser-core/std", "thiserror/std", "zerocopy/std"]
chrono = ["dep:chrono"]
time = ["dep:time"]

[lints]
workspace = true
